services:
  - type: web
    name: homabay-souq
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p media/store_logos media/store_covers
      python manage.py migrate --noinput
    startCommand: gunicorn homabay_souq.wsgi:application